### ISSUE TITLE
Unclear how to add a key + value

### ISSUE THREAD

**Issue by marcelloh** [chmike/securecookie#17]
So I have the store.
But I expected to be able to store a key + value in that store,
but I only see examples on a value only.

or Do I totally misunderstand and don't I have a store but only a single cookie when
securecookie.New() called.

I would like to save like this ("name", "Marcello") or something...

**Comment by chmike** [comment]
Sorry for the long delay to answer your question. I only noticed it today. The github notification must have been moved into the spam folder. 

I don’t understand what you mean by *store*. The `securecookie.New()` function creates a cookie object. That cookie is local to the server only and has no value associated yet. 

Once you have that cookie, you can send the cookie with a value to the client and read it back. Here is a full example code:

```go
package main

import (
	"fmt"
	"html"
	"log"
	"net/http"

	"github.com/chmike/securecookie"
)

var key []byte = securecookie.MustGenerateRandomKey()

var myCookie = securecookie.MustNew("name", key, securecookie.Params{
	Path:     "/val",      // cookie to be sent back only when URL starts with this path
	Domain:   "localhost", // cookie to be sent back only when URL domain matches this one
	MaxAge:   3600,        // cookie becomes invalid 3600 seconds after it is set
	HTTPOnly: true,        // disallow access by remote javascript code
	Secure:   false,       // cookie received with HTTP for testing purpose
})

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		if err := myCookie.SetValue(w, []byte("Marcello")); err != nil {
			log.Fatal("unexpected error: ", err)
		}
		fmt.Fprintln(w, "A secure cookie has been sent")
	})
	http.HandleFunc("/val", func(w http.ResponseWriter, r *http.Request) {
		val, err := myCookie.GetValue(nil, r)
		if err != nil {
			log.Fatal("unexpected error: ", err)
		}
		fmt.Fprintf(w, "The cookie value, %s", html.EscapeString(string(val)))
	})
	log.Fatal(http.ListenAndServe(":8080", nil))
}
```

Here is the steps to follow to run an test the code: 

1. Store the above code in a file named *main.go*
2. Create a dummy `go.mod` file with the command `go mod init example.com`
3. Start the web server with the command `go run main.go`
4. Using your preferred navigator, connect to `http://localhost:8080`, you should see a message telling you that the cookie has been sent to the navigator
5. Connect to `http://localhost:8080/val` to get a message that shows you the value of the cookie

With the development tools of the navigator, you can check that the cookie has been sent. The value it cryptic because it has been encrypted. That’s the purpose of a secure cookie.
