### ISSUE TITLE
Cookie age

### ISSUE THREAD

**Issue by druppy** [chmike/securecookie#20]
Hi ...

Thanks for taking the time to make this small but useful library !

The model is really nice, when I set cookies on response I like to only do so when needed, I really like to know how old a given cookie is in order to keep some kind of track on this, and make it possible to set new cookie based on age (like 10 min before expire).

I know this is found inside the encoding as the stamp, but I can't react on it as for now.

It would be nice with a `obj.Age(r *http.Request) int` or even a `obj.ValueAndAge(r *http.Request) (val []byte, int)` to keep performance and compatibility in mind.

Until then, I will set cookie on each response :-)

**Comment by chmike** [comment]
Thank you for the kind feedback. 

I do save the time when the cookie value was written and sent in the cookie. But I currently don't give access to that information. I don't want to modify the API for backward compatibility. But I could add a method to return the stamp + MaxAge value. I guess this would answer your demand.

There are two other solutions that doesn't require to modify the secureCookie package:

1. you could add your own stamp in the cookie value. Needs marshaling/unmarshaling. 
2. you could add a stamp to the session information stored in the server. Needs a session information. 

The stamp you store in the cookie value or the session info could be subtracted by the 10min so that all you need is to compare `Now` with that value. 

Would any of these two solutions be applicable to your use case ?

**Comment by chmike** [comment]
Is it ok if I add the method `obj.GetValueAndStamp(...)` ? Or do you prefer that I add MaxAge to stamp ?

**Comment by chmike** [comment]
I prefer returning the stamp because some times MaxAge can be zero. This happens with session cookies.

**Comment by druppy** [comment]
That would be so nice, as long as it all is relative to current system time (`time.Now() - stamp`), then I will make the calculation my self, a really elegant solution, thanks.

**Comment by chmike** [comment]
The method has been added and is available with release v1.3.3
